### ISSUE TITLE
Thanks for the awesome reproduction!

### ISSUE THREAD

**Issue by tanshuai0219** [johndpope/implicit-motion-function#1]

**Comment by johndpope** [comment]
your welcome. 
except it's blowing up with memory problems.
i think the stylegan2 - vanilla might be safer 'canonical' path. 
with all these codebases - there's parts missing. 
from diagram it could be 3 layers on some things - 
this paper is mentioned FOMM
https://github.com/ChengBinJin/image-animation

also i wonder if they could have just use a resnet as basis for dense feature extractor....

**Comment by tanshuai0219** [comment]
> your welcome. except it's blowing up with memory problems. i think the stylegan2 - vanilla might be safer 'canonical' path. with all these codebases - there's parts missing. from diagram it could be 3 layers on some things - this paper is mentioned FOMM https://github.com/ChengBinJin/image-animation
> 
> also i wonder if they could have just use a resnet as basis for dense feature extractor....

Actually, I am more interested in Implicit Motion Alignment, but it seems that the current reproduction has some discrepancies with the original paper, such as in cross-attention, self-attention, and transformer block. However, that's okay, I can make the modifications myself. I still want to thank you for providing the framework.

**Comment by johndpope** [comment]
do share. i would love to see this working.

**Comment by tanshuai0219** [comment]
> do share. i would love to see this working.

Okay~ But I think this is difficult to reproduce because the original paper doesn't provide much detail, including the dimensions of the different variables, which makes reproduction more difficult

**Comment by johndpope** [comment]
i have updates - will post in other ticket.
