### ISSUE TITLE
Question on Noise Injection block in StyledConv

### ISSUE THREAD

**Issue by vinayak-sharan** [johndpope/implicit-motion-function#40]
Hey @johndpope, I noticed that you used NoiseInjectionBlock with StyledConv.

In [supplementary](https://openaccess.thecvf.com/content/CVPR2024/supplemental/Gao_Implicit_Motion_Function_CVPR_2024_supplemental.pdf), the authors did not mention the noise block in the LatentTokenDecoder architecture.

Yue Gao also mentioned that the noise was turned off [here](https://github.com/hologerry/IMF/issues/4#issuecomment-2294659091)

Did you experiment without the Noise Block?

**Comment by johndpope** [comment]
didn't use noise. i suspect performance / generalization would drastically improve with ada -
 it's not so hard to add. one thing with the results i achieved - it doesn't seem as sharp as original image. 
also this entire algorithm begs the question if we can do higher res. didn't try.

**Comment by vinayak-sharan** [comment]
To avoid nan issues in mixed precision mode "batchnorm" can be used just before last upsample layer of the frame decoder ;)
We can definitely use sub-pixel convolution for 512x512

**Comment by johndpope** [comment]
Thanks that could be very helpful.
